language: node_js
node_js: '8'
sudo: false

git:
  depth: 50

before_script:
  - yarn global add bower
  - bower install

script:
  - "bash _build/deploy.sh"

branches:
  only:
    - master
    - staging

# directoris are node modules and bower as defined in .bowerrc
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
    - wp-content/themes/timber/assets/vendor

notifications:
  email: false
  slack: account:key
