name: Production Deploy to WP Engine

on:
  push:
    branches:
      - master

jobs:
  wp_engine_build_deploy:
    runs-on: ubuntu-latest
    name: Deploy to WP Engine
    steps:
      # To use this repository's private action, you must check out the repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - run: yarn
      - run: gulp release
      - name: WP Engine
        uses: "patronage/bubs-wpengine-deploy@master"
        env:
          WPENGINE_SSH_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
          WPENGINE_SSH_KEY_PUBLIC: ${{ secrets.WPENGINE_SSH_KEY_PUBLIC }}
          WPENGINE_ENVIRONMENT_NAME: bubs
          LOCAL_BRANCH: master
      - name: Slack Notification
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: good
          SLACK_TITLE: "Build succeeded:"
          SLACK_USERNAME: "Github Actions"
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: danger
          SLACK_TITLE: "Build failed:"
          SLACK_USERNAME: "Github Actions"
